### ISSUE TITLE
Results when creating perturbed magnitude tables for subgroups of data

### ISSUE THREAD

**Issue by tenderle** [sdcTools/cellKey#4]
@bernhard-da When using the `by` argument and creating perturbed magnitude tables directly one after another,  I don't get the appropriate results. E.g. for `by="cnt_posincome"` or `by="cnt_females"` the results are not the ones I should get. 

Here is the example:
```
library(cellKey)


## loading testdata and adding record keys (for abs-algorithm)
dat <- ck_create_testdata()

## create some 0/1 variables that should be perturbed later
dat[,cnt_females:=ifelse(sex=="male", 0, 1)]
dat[,cnt_males:=ifelse(sex=="male", 1, 0)]
dat[,cnt_highincome:=ifelse(income>=9000, 1, 0)]
dat[,cnt_posincome:=ifelse(income>0, 1, 0)]

pert_params_destatis <- ck_create_pert_params(
  smallN=12,
  pTable=ck_create_pTable(type="destatis"),
  sTable=ck_generate_sTable(smallC=12),
  mTable=c(0.6,0.4,0.2))

inp_destatis <- ck_create_input(dat=dat,def_rkey=9,pert_params=pert_params_destatis)

dim.sex <- ck_create_node(total_lab="Total")
dim.sex <- ck_add_nodes(dim.sex, reference_node="Total", node_labs=c("male","female"))

dim.age <- ck_create_node(total_lab="Total")
dim.age <- ck_add_nodes(dim.age,reference_node="Total", node_labs=paste0("age_group",1:6))

## define required inputs
dimList <- list(sex=dim.sex, age=dim.age)
weightVar <- "sampling_weight"
numVars <- c("savings", "income")

## create perturbed magnitude table for subgroups of data
res <- perturbTable(
  inp=inp_destatis,
  dimList=dimList,
  weightVar=weightVar,
  countVars=c("cnt_females", "cnt_males","cnt_highincome"),
  numVars=numVars, by="cnt_males")

ck_cont_table(res, vname="income")


res <- perturbTable(
  inp=inp_destatis,
  dimList=dimList,
  weightVar=weightVar,
  countVars=c("cnt_females", "cnt_males","cnt_highincome","cnt_posincome"),
  numVars=numVars, by="cnt_posincome")

ck_cont_table(res, vname="income")


res <- perturbTable(
  inp=inp_destatis,
  dimList=dimList,
  weightVar=weightVar,
  countVars=c("cnt_females", "cnt_males","cnt_highincome","cnt_posincome"),
  numVars=numVars, by="cnt_females")

ck_cont_table(res, vname="income")
```

If you reorder `res <- perturbTable()` and run the whole example you get the expected results for the first `res`.

**Comment by bernhard-da** [comment]
@tenderle thx for spotting this bug which should be fixed in the features branch.

**Comment by tenderle** [comment]
Ah, ok. then I have to ask because I am interested. You added the `copy()` in order to work with the copy of the `inp`-slot `microdata`. What was the issue? The `inp`-object in the memory was still the same.

**Comment by bernhard-da** [comment]
@tenderle the `inp@microdat` slot is a `data.table` so any modifications on this object are done by reference which leads to exactly the bug in this issue. you still have `inp_destatis` in your environment but it got changed within the `perturbTable` function. by using an explicit `copy()`, the content of this slot is copied (to a different place in the memory) and thus the `inp` -object fed to the function is not modified.

**Comment by tenderle** [comment]
Thx @bernhard-da lesson learned ;-) Unfortunately tried to copy the `inp_destatis` with a simple `<- inp_destatis` before and after each perturbation in order to compare them with `all.equal()` aftwerwards. Also here I need a ` <- copy(ind_destatis)` otherwise I just bind another name to the same object, namely `inp_destatis`.
